### **02.1 download and read the CSV file and make ID the index column**

In [1]:
import pandas as pd
df = pd.read_csv("../../datasets/auto.csv", index_col=0)
df

        CarNumber    Make_n_model  Refund    Fines  History
ID
0    Y163O8161RUS      Ford Focus     2.0   3200.0      NaN
1     E432XX77RUS    Toyota Camry     1.0   6500.0      NaN
2     7184TT36RUS      Ford Focus     1.0   2100.0      NaN
3    X582HE161RUS      Ford Focus     2.0   2000.0      NaN
4    E34877152RUS      Ford Focus     2.0   6100.0      NaN
..            ...             ...     ...      ...      ...
926  Y163O8161RUS      Ford Focus     2.0   1600.0      NaN
927  M0309X197RUS      Ford Focus     1.0  22300.0      NaN
928  O673E8197RUS      Ford Focus     2.0    600.0      NaN
929  8610T8154RUS      Ford Focus     1.0   2000.0      NaN
930  H419XE197RUS  Toyota Corolla     2.0      NaN      2.0

[931 rows x 5 columns]

### **02.2 count the number of observations using the method count()**

In [2]:
df.count()

CarNumber       931
Make_n_model    931
Refund          914
Fines           869
History          82
dtype: int64

### **02.3 drop the duplicates, taking into account only the following columns: CarNumber, Make_n_model, Fines**

In [3]:
# between the two equal observations, you need to choose the last
df.drop_duplicates(['CarNumber','Make_n_model','Fines'], keep='last', inplace=True)
df

        CarNumber    Make_n_model  Refund    Fines  History
ID
0    Y163O8161RUS      Ford Focus     2.0   3200.0      NaN
1     E432XX77RUS    Toyota Camry     1.0   6500.0      NaN
2     7184TT36RUS      Ford Focus     1.0   2100.0      NaN
3    X582HE161RUS      Ford Focus     2.0   2000.0      NaN
5    92918M178RUS      Ford Focus     1.0   5700.0      NaN
..            ...             ...     ...      ...      ...
926  Y163O8161RUS      Ford Focus     2.0   1600.0      NaN
927  M0309X197RUS      Ford Focus     1.0  22300.0      NaN
928  O673E8197RUS      Ford Focus     2.0    600.0      NaN
929  8610T8154RUS      Ford Focus     1.0   2000.0      NaN
930  H419XE197RUS  Toyota Corolla     2.0      NaN      2.0

[725 rows x 5 columns]

In [4]:
# check the number of observations again
df.count()

CarNumber       725
Make_n_model    725
Refund          713
Fines           665
History          65
dtype: int64

### **02.4 work with missing values**

In [5]:
# check how many values are missing from each column
df.isnull().sum()

CarNumber         0
Make_n_model      0
Refund           12
Fines            60
History         660
dtype: int64

In [6]:
# drop all the columns with over 500 missing values using the argument thresh, check how many missing values are in each column
df.dropna(thresh=500 ,axis=1, inplace=True)
df.isnull().sum()

CarNumber        0
Make_n_model     0
Refund          12
Fines           60
dtype: int64

In [7]:
# replace all the missing values in the Refund column with the previous value in that column for that cell, use the argument method, 
# check how many values are missing from each column
df['Refund'] = df['Refund'].ffill()
df.isnull().sum()

CarNumber        0
Make_n_model     0
Refund           0
Fines           60
dtype: int64

In [8]:
# replace all the missing values in the Fines column with the mean value of this column 
# (exclude NA/null values when computing the mean value), check how many values are missing from each column
df['Fines'] = df['Fines'].fillna(df['Fines'].mean())
df.isnull().sum()

CarNumber       0
Make_n_model    0
Refund          0
Fines           0
dtype: int64

### **02.5 split and parse the make and model**

In [9]:
# use the method apply both for splitting and for extracting the values to the new columns Make and Model
df['Make_n_model'] = df['Make_n_model'].apply(lambda x: x.split())                          
df

        CarNumber       Make_n_model  Refund         Fines
ID
0    Y163O8161RUS      [Ford, Focus]     2.0   3200.000000
1     E432XX77RUS    [Toyota, Camry]     1.0   6500.000000
2     7184TT36RUS      [Ford, Focus]     1.0   2100.000000
3    X582HE161RUS      [Ford, Focus]     2.0   2000.000000
5    92918M178RUS      [Ford, Focus]     1.0   5700.000000
..            ...                ...     ...           ...
926  Y163O8161RUS      [Ford, Focus]     2.0   1600.000000
927  M0309X197RUS      [Ford, Focus]     1.0  22300.000000
928  O673E8197RUS      [Ford, Focus]     2.0    600.000000
929  8610T8154RUS      [Ford, Focus]     1.0   2000.000000
930  H419XE197RUS  [Toyota, Corolla]     2.0   8594.586466

[725 rows x 4 columns]

In [10]:
df[['Make', 'Model']] = df['Make_n_model'].apply(lambda x: pd.Series([i for i in x]))
df

        CarNumber       Make_n_model  Refund         Fines    Make    Model
ID
0    Y163O8161RUS      [Ford, Focus]     2.0   3200.000000    Ford    Focus
1     E432XX77RUS    [Toyota, Camry]     1.0   6500.000000  Toyota    Camry
2     7184TT36RUS      [Ford, Focus]     1.0   2100.000000    Ford    Focus
3    X582HE161RUS      [Ford, Focus]     2.0   2000.000000    Ford    Focus
5    92918M178RUS      [Ford, Focus]     1.0   5700.000000    Ford    Focus
..            ...                ...     ...           ...     ...      ...
926  Y163O8161RUS      [Ford, Focus]     2.0   1600.000000    Ford    Focus
927  M0309X197RUS      [Ford, Focus]     1.0  22300.000000    Ford    Focus
928  O673E8197RUS      [Ford, Focus]     2.0    600.000000    Ford    Focus
929  8610T8154RUS      [Ford, Focus]     1.0   2000.000000    Ford    Focus
930  H419XE197RUS  [Toyota, Corolla]     2.0   8594.586466  Toyota  Corolla

[725 rows x 6 columns]

In [11]:
# drop the column Make_n_model
del df['Make_n_model']
df

        CarNumber  Refund         Fines    Make    Model
ID
0    Y163O8161RUS     2.0   3200.000000    Ford    Focus
1     E432XX77RUS     1.0   6500.000000  Toyota    Camry
2     7184TT36RUS     1.0   2100.000000    Ford    Focus
3    X582HE161RUS     2.0   2000.000000    Ford    Focus
5    92918M178RUS     1.0   5700.000000    Ford    Focus
..            ...     ...           ...     ...      ...
926  Y163O8161RUS     2.0   1600.000000    Ford    Focus
927  M0309X197RUS     1.0  22300.000000    Ford    Focus
928  O673E8197RUS     2.0    600.000000    Ford    Focus
929  8610T8154RUS     1.0   2000.000000    Ford    Focus
930  H419XE197RUS     2.0   8594.586466  Toyota  Corolla

[725 rows x 5 columns]

In [12]:
# save the dataframe in the JSON file auto.json in the format below:

[{"CarNumber":"Y163O8161RUS","Refund":2.0,"Fines":3200.0,"Make":"Ford",
"Model":"Focus"},
{"CarNumber":"E432XX77RUS","Refund":1.0,"Fines":6500.0,"Make":"Toyota",
"Model":"Camry"}]

In [13]:
df.to_json('../../datasets/auto.json', orient="records", double_precision=1)