## **Exercise 03 : Selects and aggregations**

### **03.1 Load the JSON file that you created in the previous exercise into a dataframe**

In [1]:
# set CarNumber as the index column
import pandas as pd
df = pd.read_json('../../datasets/auto.json', orient="records")
df.set_index('CarNumber', inplace=True)
df['Refund'] = df['Refund'].astype(float)
df

              Refund    Fines    Make    Model
CarNumber
Y163O8161RUS     2.0   3200.0    Ford    Focus
E432XX77RUS      1.0   6500.0  Toyota    Camry
7184TT36RUS      1.0   2100.0    Ford    Focus
X582HE161RUS     2.0   2000.0    Ford    Focus
92918M178RUS     1.0   5700.0    Ford    Focus
...              ...      ...     ...      ...
Y163O8161RUS     2.0   1600.0    Ford    Focus
M0309X197RUS     1.0  22300.0    Ford    Focus
O673E8197RUS     2.0    600.0    Ford    Focus
8610T8154RUS     1.0   2000.0    Ford    Focus
H419XE197RUS     2.0   8594.6  Toyota  Corolla

[725 rows x 4 columns]

### **03.2 Make the following selects**

In [2]:
# display the rows only where the fines are more than 2,100
df.loc[df['Fines'] > 2100]

              Refund    Fines        Make    Model
CarNumber
Y163O8161RUS     2.0   3200.0        Ford    Focus
E432XX77RUS      1.0   6500.0      Toyota    Camry
92918M178RUS     1.0   5700.0        Ford    Focus
H234YH197RUS     2.0   6000.0        Ford    Focus
E40577152RUS     1.0   8594.6        Ford    Focus
...              ...      ...         ...      ...
O718MM163RUS     2.0   8594.6        Ford    Focus
7065C8197RUS     2.0  11400.0  Volkswagen   Passat
O22097197RUS     1.0  24300.0        Ford    Focus
M0309X197RUS     1.0  22300.0        Ford    Focus
H419XE197RUS     2.0   8594.6      Toyota  Corolla

[455 rows x 4 columns]

In [3]:
# display the rows only where the fines are more than 2,100 and the refund equals 2
df.loc[(df['Fines'] > 2100) & (df['Refund'] == 2)]

              Refund    Fines        Make    Model
CarNumber
Y163O8161RUS     2.0   3200.0        Ford    Focus
H234YH197RUS     2.0   6000.0        Ford    Focus
707987163RUS     2.0   2200.0        Ford    Focus
K330T8197RUS     2.0   8200.0       Skoda  Octavia
M592CH197RUS     2.0   8594.6       Skoda  Octavia
...              ...      ...         ...      ...
O136HO197RUS     2.0   7800.0      Toyota  Corolla
O68897197RUS     2.0  12300.0        Ford    Focus
O718MM163RUS     2.0   8594.6        Ford    Focus
7065C8197RUS     2.0  11400.0  Volkswagen   Passat
H419XE197RUS     2.0   8594.6      Toyota  Corolla

[309 rows x 4 columns]

In [4]:
# display the rows only where the models are from the list: [’Focus’, ’Corolla’]
df.loc[df['Model'].isin(['Focus', 'Corolla'])]

              Refund    Fines    Make    Model
CarNumber
Y163O8161RUS     2.0   3200.0    Ford    Focus
7184TT36RUS      1.0   2100.0    Ford    Focus
X582HE161RUS     2.0   2000.0    Ford    Focus
92918M178RUS     1.0   5700.0    Ford    Focus
H234YH197RUS     2.0   6000.0    Ford    Focus
...              ...      ...     ...      ...
Y163O8161RUS     2.0   1600.0    Ford    Focus
M0309X197RUS     1.0  22300.0    Ford    Focus
O673E8197RUS     2.0    600.0    Ford    Focus
8610T8154RUS     1.0   2000.0    Ford    Focus
H419XE197RUS     2.0   8594.6  Toyota  Corolla

[593 rows x 4 columns]

In [5]:
# display the rows only where the car number is from the list: [’Y7689C197RUS’, ’92928M178RUS’, ’7788KT197RUS’, ’H115YO163RUS’, ’X758HY197RUS’]
df.loc[df.index.isin(['Y7689C197RUS', '92928M178RUS', '7788KT197RUS', 'H115YO163RUS', 'X758HY197RUS'])]

              Refund     Fines  Make  Model
CarNumber
92928M178RUS     1.0    8594.6  Ford  Focus
H115YO163RUS     1.0    2200.0  Ford  Focus
7788KT197RUS     2.0   12000.0  Ford  Focus
X758HY197RUS     2.0   24200.0  Ford  Focus
X758HY197RUS     2.0   72600.0  Ford  Focus
Y7689C197RUS     1.0   27000.0  Ford  Focus
92928M178RUS     1.0     600.0  Ford  Focus
H115YO163RUS     1.0    8594.6  Ford  Focus
H115YO163RUS     2.0    1100.0  Ford  Focus
7788KT197RUS     2.0    8594.6  Ford  Focus
7788KT197RUS     1.0   20000.0  Ford  Focus
X758HY197RUS     2.0  145200.0  Ford  Focus
92928M178RUS     1.0    1200.0  Ford  Focus
Y7689C197RUS     2.0    9000.0  Ford  Focus
Y7689C197RUS     2.0   45000.0  Ford  Focus
7788KT197RUS     2.0    4000.0  Ford  Focus
Y7689C197RUS     1.0   36000.0  Ford  Focus
92928M178RUS     2.0    3000.0  Ford  Focus

### **03.3 Make the aggregations with the make and the model**

In [6]:
# display the median fines grouped by the make
df.groupby(['Make']).agg('Fines').median()

Make
Audi          4200.0
BMW           6500.0
Ford          3500.0
Skoda         3250.0
Toyota        7700.0
Volkswagen    4300.0
Volvo         8500.0
Name: Fines, dtype: float64

In [7]:
# display the median fines grouped by the make and the model
df.groupby(['Make', 'Model']).agg('Fines').median()

Make        Model
Ford        Focus      3500.0
            Mondeo     7650.0
Skoda       Octavia    3250.0
Toyota      Camry      7700.0
            Corolla    7700.0
Volkswagen  Golf       4800.0
            Jetta      2800.0
            Passat     3500.0
            Touareg    5800.0
Name: Fines, dtype: float64

In [8]:
# display the number of fines grouped by the make and the model in order to understand if we can trust the median values
df.groupby(['Make', 'Model']).agg('Fines').count()

Make        Model
Ford        Focus      575
            Mondeo       6
Skoda       Octavia     48
Toyota      Camry       16
            Corolla     18
Volkswagen  Golf        20
            Jetta        6
            Passat      22
            Touareg      5
Name: Fines, dtype: int64

In [9]:
# display the minimum and the maximum fines grouped by the make and the model in order to better understand the variance
pd.concat([df.groupby(['Make', 'Model']).agg('Fines').min(), df.groupby(['Make', 'Model']).agg('Fines').max()], keys=['min', 'max'], axis=1)

                       min       max
Make       Model
Ford       Focus     100.0  180000.0
           Mondeo   1100.0   46200.0
Skoda      Octavia   300.0  145000.0
Toyota     Camry     500.0   22400.0
           Corolla   900.0   34300.0
Volkswagen Golf      200.0  168000.0
           Jetta     500.0   46000.0
           Passat    100.0   29700.0
           Touareg   500.0    8594.6

In [10]:
# display the standard deviation of the fines grouped by the make and the model in order to better understand the variance
df.groupby(['Make', 'Model']).agg('Fines').std()

Make        Model
Ford        Focus      15041.269466
            Mondeo     18987.329108
Skoda       Octavia    24339.742009
Toyota      Camry       6410.250754
            Corolla     9629.325453
Volkswagen  Golf       36950.839812
            Jetta      17743.026799
            Passat      6969.739548
            Touareg     3461.782176
Name: Fines, dtype: float64

### **03.4 Make the aggregations with the car number**

In [11]:
# display the car numbers grouped by the number of the fines in descending order, we want to find those who most often violated the law
group1 = df.groupby(['CarNumber']).agg('Fines').count().sort_values(ascending=False)
group1

CarNumber
Y7689C197RUS    4
7788KT197RUS    4
92928M178RUS    4
Y7129Y50RUS     3
X758HY197RUS    3
               ..
Y967O8197RUS    1
Y965O8197RUS    1
Y965EE197RUS    1
Y964O8197RUS    1
Y964EE197RUS    1
Name: Fines, Length: 531, dtype: int64

In [12]:
# select from the initial dataframe all the rows corresponding to the top-1 car number, we want to zoom in a little bit
df.loc[df.index == group1.index[0]]

              Refund    Fines  Make  Model
CarNumber
Y7689C197RUS     1.0  27000.0  Ford  Focus
Y7689C197RUS     2.0   9000.0  Ford  Focus
Y7689C197RUS     2.0  45000.0  Ford  Focus
Y7689C197RUS     1.0  36000.0  Ford  Focus

In [13]:
# display the car numbers grouped by the sum of the fines in descending order, we want to find those who paid the most
group2 = df.groupby(['CarNumber']).agg('Fines').sum().sort_values(ascending=False)
group2

CarNumber
X758HY197RUS    242000.0
9020YC197RUS    217500.0
M0279X197RUS    216000.0
Y352O8197RUS    207200.0
Y778EE197RUS    192000.0
                  ...
Y166O8161RUS       100.0
K326T8197RUS       100.0
Y195O8161RUS       100.0
C58078163RUS       100.0
705787163RUS       100.0
Name: Fines, Length: 531, dtype: float64

In [14]:
# select from the initial dataframe all the rows corresponding to the top-1 car number, we want to zoom in a little bit
df.loc[df.index == group2.index[0]]

              Refund     Fines  Make  Model
CarNumber
X758HY197RUS     2.0   24200.0  Ford  Focus
X758HY197RUS     2.0   72600.0  Ford  Focus
X758HY197RUS     2.0  145200.0  Ford  Focus

In [15]:
# display a table that answers the question: are there any car numbers that were connected to different models?
num = df.reset_index().drop_duplicates(['CarNumber','Make', 'Model'], keep='last').groupby('CarNumber').count().sort_values('Model', ascending=False)
num

              Refund  Fines  Make  Model
CarNumber
Y973O8197RUS       1      1     1      1
704687163RUS       1      1     1      1
704787163RUS       1      1     1      1
Y7699C197RUS       1      1     1      1
Y7689C197RUS       1      1     1      1
...              ...    ...   ...    ...
M5039X197RUS       1      1     1      0
H837YK197RUS       1      1     1      0
96907X197RUS       1      1     1      0
Y687HM197RUS       1      1     1      0
Y693HM197RUS       1      1     1      0

[531 rows x 4 columns]